# Build stage
FROM golang:1.17-alpine AS build
RUN apk update && apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod .
RUN go mod download

COPY . .
ARG CGO_ENABLED=1
RUN go build -o tt ./cmd/tt

# Test stage
FROM golang:1.17-alpine

WORKDIR /app

COPY --from=build /app /app

RUN apk add --no-cache curl
RUN apk update && apk add --no-cache gcc musl-dev

ENTRYPOINT [ "sh", "-c" ]
CMD ["go test -json -v -count=1 ./internal/..."]

